### ISSUE TITLE
casarest needs to depend on libcasacore2

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro-debian/casarest-debian#4]
At the moment it installs without.

**Comment by gijzelaerr** [comment]
ok small typo

https://github.com/radio-astro-debian/casarest-debian/commit/1a496efa448066f27a5b7f4d93bbe8a5ae5e0d3c

uploaded new version to the PPA.

https://launchpad.net/~radio-astro/+archive/ubuntu/main/+build/7886484
