### ISSUE TITLE
post-lwimager-merge release requested

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro-debian/casarest-debian#5]
Current lwimager is exclusive with casarest and lofar, which kinds of sucks for me, because I need the functionality of both.

Now that I've merged the missing lwimager functionality into casarest (https://github.com/casacore/casarest/pull/4), it would be good to roll a new casarest package and retire the lwimager package.

**Comment by gijzelaerr** [comment]
casarest 1.4.0 has been released and packages. left to do is remove the old lwimager package.

**Comment by gijzelaerr** [comment]
lwimager 1.3 and 1.2 have been removed from the PPA
